#-*- encoding:UTF-8 -*-
'''
Created on 2019/6/18

@author: xcKev
'''

class HtmlTypes():
    def __init__(self):
        self.content_types={
".*":"application/octet-stream",
".001":"application/x-001",
".323":"text/h323",
".907":"drawing/907",
".acp":"audio/x-mei-aac",
".aif":"audio/aiff",
".aiff":"audio/aiff",
".asa":"text/asa",
".asp":"text/asp",
".au":"audio/basic",
".awf":"application/vnd.adobe.workflow",
".bmp":"application/x-bmp",
".c4t":"application/x-c4t",
".cal":"application/x-cals",
".cdf":"application/x-netcdf",
".cel":"application/x-cel",
".cg4":"application/x-g4",
".cit":"application/x-cit",
".cml":"text/xml",
".cmx":"application/x-cmx",
".crl":"application/pkix-crl",
".csi":"application/x-csi",
".cut":"application/x-cut",
".dbm":"application/x-dbm",
".dcd":"text/xml",
".der":"application/x-x509-ca-cert",
".dib":"application/x-dib",
".doc":"application/msword",
".drw":"application/x-drw",
".dwf":"Model/vnd.dwf",
".dwg":"application/x-dwg",
".dxf":"application/x-dxf",
".emf":"application/x-emf",
".ent":"text/xml",
".eps":"application/x-ps",
".etd":"application/x-ebx",
".fax":"image/fax",
".fif":"application/fractals",
".frm":"application/x-frm",
".gbr":"application/x-gbr",
".gif":"image/gif",
".gp4":"application/x-gp4",
".hmr":"application/x-hmr",
".hpl":"application/x-hpl",
".hrf":"application/x-hrf",
".htc":"text/x-component",
".html":"text/html",
".htx":"text/html",
".ico":"image/x-icon",
".iff":"application/x-iff",
".igs":"application/x-igs",
".img":"application/x-img",
".isp":"application/x-internet-signup",
".java":"java/*",
".jpe":"image/jpeg",
".jpeg":"image/jpeg",
".jpg":"application/x-jpg",
".jsp":"text/html",
".lar":"application/x-laplayer-reg",
".lavs":"audio/x-liquid-secure",
".lmsff":"audio/x-la-lms",
".ltr":"application/x-ltr",
".m2v":"video/x-mpeg",
".m4e":"video/mpeg4",
".man":"application/x-troff-man",
".mdb":"application/msaccess",
".mfp":"application/x-shockwave-flash",
".mhtml":"message/rfc822",
".mid":"audio/mid",
".mil":"application/x-mil",
".mnd":"audio/x-musicnet-download",
".mocha":"application/x-javascript",
".mp1":"audio/mp1",
".mp2v":"video/mpeg",
".mp4":"video/mpeg4",
".mpd":"application/vnd.ms-project",
".mpeg":"video/mpg",
".mpga":"audio/rn-mpeg",
".mps":"video/x-mpeg",
".mpv":"video/mpg",
".mpw":"application/vnd.ms-project",
".mtx":"text/xml",
".net":"image/pnetvue",
".nws":"message/rfc822",
".out":"application/x-out",
".p12":"application/x-pkcs12",
".p7c":"application/pkcs7-mime",
".p7r":"application/x-pkcs7-certreqresp",
".pc5":"application/x-pc5",
".pcl":"application/x-pcl",
".pdf":"application/pdf",
".pdx":"application/vnd.adobe.pdx",
".pgl":"application/x-pgl",
".pko":"application/vnd.ms-pki.pko",
".plg":"text/html",
".plt":"application/x-plt",
".png":"application/x-png",
".ppa":"application/vnd.ms-powerpoint",
".pps":"application/vnd.ms-powerpoint",
".ppt":"application/x-ppt",
".prf":"application/pics-rules",
".prt":"application/x-prt",
".ps":"application/postscript",
".pwz":"application/vnd.ms-powerpoint",
".ra":"audio/vnd.rn-realaudio",
".ras":"application/x-ras",
".rdf":"text/xml",
".red":"application/x-red",
".rjs":"application/vnd.rn-realsystem-rjs",
".rlc":"application/x-rlc",
".rm":"application/vnd.rn-realmedia",
".rmi":"audio/mid",
".rmm":"audio/x-pn-realaudio",
".rms":"application/vnd.rn-realmedia-secure",
".rmx":"application/vnd.rn-realsystem-rmx",
".rp":"image/vnd.rn-realpix",
".rsml":"application/vnd.rn-rsml",
".rtf":"application/msword",
".rv":"video/vnd.rn-realvideo",
".sat":"application/x-sat",
".sdw":"application/x-sdw",
".slb":"application/x-slb",
".slk":"drawing/x-slk",
".smil":"application/smil",
".snd":"audio/basic",
".sor":"text/plain",
".spl":"application/futuresplash",
".ssm":"application/streamingmedia",
".stl":"application/vnd.ms-pki.stl",
".sty":"application/x-sty",
".swf":"application/x-shockwave-flash",
".tg4":"application/x-tg4",
".tif":"image/tiff",
".tiff":"image/tiff",
".top":"drawing/x-top",
".tsd":"text/xml",
".uin":"application/x-icq",
".vcf":"text/x-vcard",
".vdx":"application/vnd.visio",
".vpg":"application/x-vpeg005",
".vsd":"application/x-vsd",
".vst":"application/vnd.visio",
".vsw":"application/vnd.visio",
".vtx":"application/vnd.visio",
".wav":"audio/wav",
".wb1":"application/x-wb1",
".wb3":"application/x-wb3",
".wiz":"application/msword",
".wk4":"application/x-wk4",
".wks":"application/x-wks",
".wma":"audio/x-ms-wma",
".wmf":"application/x-wmf",
".wmv":"video/x-ms-wmv",
".wmz":"application/x-ms-wmz",
".wpd":"application/x-wpd",
".wpl":"application/vnd.ms-wpl",
".wr1":"application/x-wr1",
".wrk":"application/x-wrk",
".ws2":"application/x-ws",
".wsdl":"text/xml",
".xdp":"application/vnd.adobe.xdp",
".xfd":"application/vnd.adobe.xfd",
".xhtml":"text/html",
".xls":"application/x-xls",
".xml":"text/xml",
".xq":"text/xml",
".xquery":"text/xml",
".xsl":"text/xml",
".xwd":"application/x-xwd",
".sis":"application/vnd.symbian.install",
".x_t":"application/x-x_t",
".apk":"application/vnd.android.package-archive",
".tif":"image/tiff",
".301":"application/x-301",
".906":"application/x-906",
".a11":"application/x-a11",
".ai":"application/postscript",
".aifc":"audio/aiff",
".anv":"application/x-anv",
".asf":"video/x-ms-asf",
".asx":"video/x-ms-asf",
".avi":"video/avi",
".biz":"text/xml",
".bot":"application/x-bot",
".c90":"application/x-c90",
".cat":"application/vnd.ms-pki.seccat",
".cdr":"application/x-cdr",
".cer":"application/x-x509-ca-cert",
".cgm":"application/x-cgm",
".class":"java/*",
".cmp":"application/x-cmp",
".cot":"application/x-cot",
".crt":"application/x-x509-ca-cert",
".css":"text/css",
".dbf":"application/x-dbf",
".dbx":"application/x-dbx",
".dcx":"application/x-dcx",
".dgn":"application/x-dgn",
".dll":"application/x-msdownload",
".dot":"application/msword",
".dtd":"text/xml",
".dwf":"application/x-dwf",
".dxb":"application/x-dxb",
".edn":"application/vnd.adobe.edn",
".eml":"message/rfc822",
".epi":"application/x-epi",
".eps":"application/postscript",
".exe":"application/x-msdownload",
".fdf":"application/vnd.fdf",
".fo":"text/xml",
".g4":"application/x-g4",
".":"application/x-",
".gl2":"application/x-gl2",
".hgl":"application/x-hgl",
".hpg":"application/x-hpgl",
".hqx":"application/mac-binhex40",
".hta":"application/hta",
".htm":"text/html",
".htt":"text/webviewhtml",
".icb":"application/x-icb",
".ico":"application/x-ico",
".ig4":"application/x-g4",
".iii":"application/x-iphone",
".ins":"application/x-internet-signup",
".IVF":"video/x-ivf",
".jfif":"image/jpeg",
".jpe":"application/x-jpe",
".jpg":"image/jpeg",
".js":"application/x-javascript",
".la1":"audio/x-liquid-file",
".latex":"application/x-latex",
".lbm":"application/x-lbm",
".ls":"application/x-javascript",
".m1v":"video/x-mpeg",
".m3u":"audio/mpegurl",
".mac":"application/x-mac",
".math":"text/xml",
".mdb":"application/x-mdb",
".mht":"message/rfc822",
".mi":"application/x-mi",
".midi":"audio/mid",
".mml":"text/xml",
".mns":"audio/x-musicnet-stream",
".movie":"video/x-sgi-movie",
".mp2":"audio/mp2",
".mp3":"audio/mp3",
".mpa":"video/x-mpg",
".mpe":"video/x-mpeg",
".mpg":"video/mpg",
".mpp":"application/vnd.ms-project",
".mpt":"application/vnd.ms-project",
".mpv2":"video/mpeg",
".mpx":"application/vnd.ms-project",
".mxp":"application/x-mmxp",
".nrf":"application/x-nrf",
".odc":"text/x-ms-odc",
".p10":"application/pkcs10",
".p7b":"application/x-pkcs7-certificates",
".p7m":"application/pkcs7-mime",
".p7s":"application/pkcs7-signature",
".pci":"application/x-pci",
".pcx":"application/x-pcx",
".pdf":"application/pdf",
".pfx":"application/x-pkcs12",
".pic":"application/x-pic",
".pl":"application/x-perl",
".pls":"audio/scpls",
".png":"image/png",
".pot":"application/vnd.ms-powerpoint",
".ppm":"application/x-ppm",
".ppt":"application/vnd.ms-powerpoint",
".pr":"application/x-pr",
".prn":"application/x-prn",
".ps":"application/x-ps",
".ptn":"application/x-ptn",
".r3t":"text/vnd.rn-realtext3d",
".ram":"audio/x-pn-realaudio",
".rat":"application/rat-file",
".rec":"application/vnd.rn-recording",
".rgb":"application/x-rgb",
".rjt":"application/vnd.rn-realsystem-rjt",
".rle":"application/x-rle",
".rmf":"application/vnd.adobe.rmf",
".rmj":"application/vnd.rn-realsystem-rmj",
".rmp":"application/vnd.rn-rn_music_package",
".rmvb":"application/vnd.rn-realmedia-vbr",
".rnx":"application/vnd.rn-realplayer",
".rpm":"audio/x-pn-realaudio-plugin",
".rt":"text/vnd.rn-realtext",
".rtf":"application/x-rtf",
".sam":"application/x-sam",
".sdp":"application/sdp",
".sit":"application/x-stuffit",
".sld":"application/x-sld",
".smi":"application/smil",
".smk":"application/x-smk",
".sol":"text/plain",
".spc":"application/x-pkcs7-certificates",
".spp":"text/xml",
".sst":"application/vnd.ms-pki.certstore",
".stm":"text/html",
".svg":"text/xml",
".tdf":"application/x-tdf",
".tga":"application/x-tga",
".tif":"application/x-tif",
".tld":"text/xml",
".torrent":"application/x-bittorrent",
".txt":"text/plain",
".uls":"text/iuls",
".vda":"application/x-vda",
".vml":"text/xml",
".vsd":"application/vnd.visio",
".vss":"application/vnd.visio",
".vst":"application/x-vst",
".vsx":"application/vnd.visio",
".vxml":"text/xml",
".wax":"audio/x-ms-wax",
".wb2":"application/x-wb2",
".wbmp":"image/vnd.wap.wbmp",
".wk3":"application/x-wk3",
".wkq":"application/x-wkq",
".wm":"video/x-ms-wm",
".wmd":"application/x-ms-wmd",
".wml":"text/vnd.wap.wml",
".wmx":"video/x-ms-wmx",
".wp6":"application/x-wp6",
".wpg":"application/x-wpg",
".wq1":"application/x-wq1",
".wri":"application/x-wri",
".ws":"application/x-ws",
".wsc":"text/scriptlet",
".wvx":"video/x-ms-wvx",
".xdr":"text/xml",
".xfdf":"application/vnd.adobe.xfdf",
".xls":"application/vnd.ms-excel",
".xlw":"application/x-xlw",
".xpl":"audio/scpls",
".xql":"text/xml",
".xsd":"text/xml",
".xslt":"text/xml",
".x_b":"application/x-x_b",
".sisx":"application/vnd.symbian.install",
".ipa":"application/vnd.iphone",
".xap":"application/x-silverlight-app"
}
        self.pc_user_agents=[
            "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50",
"Mozilla/5.0 (Windows; U; Windows NT 6.1; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50",
"Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0;",
"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)",
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv,2.0.1) Gecko/20100101 Firefox/4.0.1",
"Mozilla/5.0 (Windows NT 6.1; rv,2.0.1) Gecko/20100101 Firefox/4.0.1",
"Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; en) Presto/2.8.131 Version/11.11",
"Opera/9.80 (Windows NT 6.1; U; en) Presto/2.8.131 Version/11.11",
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Maxthon 2.0)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; TencentTraveler 4.0)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; The World)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SE 2.X MetaSr 1.0; SE 2.X MetaSr 1.0; .NET CLR 2.0.50727; SE 2.X MetaSr 1.0)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; 360SE)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Avant Browser)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)"
            ]
        self.phone_uer_agents=[
            "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5",
"Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5",
"Mozilla/5.0 (iPad; U; CPU OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5",
"Mozilla/5.0 (Linux; U; Android 2.3.7; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1",
"MQQBrowser/26 Mozilla/5.0 (Linux; U; Android 2.3.7; zh-cn; MB200 Build/GRJ22; CyanogenMod-7) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1",
"Opera/9.80 (Android 2.3.4; Linux; Opera Mobi/build-1107180945; U; en-GB) Presto/2.8.149 Version/11.10",
"Mozilla/5.0 (Linux; U; Android 3.0; en-us; Xoom Build/HRI39) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/534.13",
"Mozilla/5.0 (BlackBerry; U; BlackBerry 9800; en) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.337 Mobile Safari/534.1+",
"Mozilla/5.0 (hp-tablet; Linux; hpwOS/3.0.0; U; en-US) AppleWebKit/534.6 (KHTML, like Gecko) wOSBrowser/233.70 Safari/534.6 TouchPad/1.0",
"Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaN97-1/20.0.019; Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/525 (KHTML, like Gecko) BrowserNG/7.1.18124",
"Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; HTC; Titan)",
"UCWEB7.0.2.37/28/999",
"NOKIA5700/ UCWEB7.0.2.37/28/999",
"Openwave/ UCWEB7.0.2.37/28/999",
"Mozilla/4.0 (compatible; MSIE 6.0; ) Opera/UCWEB7.0.2.37/28/999"
            ]
        self.ios_webchat_user_agents=[
"Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 MicroMessenger/6.6.1 NetType/4G Language/zh_CN",
"Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202 MicroMessenger/6.6.1 NetType/4G Language/zh_CN",
"Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B150 MicroMessenger/6.6.1 NetType/WIFI Language/zh_CN",
"Mozilla/5.0 (iphone x Build/MXB48T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043632 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_CN"
            ]
        self.android_webchat_user_agents=[
"Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_CN",
"Mozilla/5.0 (Linux; Android 7.1.1; OD103 Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043632 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN",
"Mozilla/5.0 (Linux; Android 6.0.1; SM919 Build/MXB48T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043632 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_CN",
"Mozilla/5.0 (Linux; Android 5.1.1; vivo X6S A Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043632 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_CN",
"Mozilla/5.0 (Linux; Android 5.1; HUAWEI TAG-AL00 Build/HUAWEITAG-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043622 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN",
"Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN miniProgram"
            ]
