delete from CommonRules;
insert into CommonRules values(1,'html5','h1','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(2,'html5','h2','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(3,'html5','h3','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(4,'html5','h4','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(5,'html5','h5','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(6,'html5','pre','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(7,'html5','p','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(8,'html5','em','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(9,'html5','strong','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(10,'html5','a','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(11,'html5','i','clean_text','clean_text','clean_text',0,'alvin',curdate());
insert into CommonRules values(12,'html5','ul','child_text','li','child_text',0,'alvin',curdate());
insert into CommonRules values(13,'html5','ol','child_text','li','child_text',0,'alvin',curdate());
insert into CommonRules values(14,'html5','table','children_text','tbody','children_text',0,'alvin',curdate());
insert into CommonRules values(15,'html5','image','dirty_text','p','dirty_text',0,'alvin',curdate());
insert into CommonRules values(16,'html5','line','no_text','no_text','no_text',0,'alvin',curdate());
insert into CommonRules values(17,'font','BOLD','html5','<strong>','html5',0,'alvin',curdate());
insert into CommonRules values(18,'font','BLUE_BG','html5','<span class="label label-info">','html5',0,'alvin',curdate());
