"""
Django settings for alvin_tool project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
import platform

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
if platform.system() == "Linux":
    PROJECT_ROOT = "/usr/local/core_pdf_page"
    PROJECT_NAME = "PdfWeb"
    PARENT_DIR = "/usr/local/core_pdf_page"
else:
    PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
    PROJECT_NAME = os.path.split(PROJECT_ROOT)[-1]
    BASE_DIR = os.path.dirname(PROJECT_ROOT)
    PARENT_DIR= os.path.dirname(BASE_DIR)
    sys.path.insert(0, os.path.join(PROJECT_ROOT, 'applications'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+u@w-=x#oby7b_%25dj-qxog7!a=g-g-imo90b_d&^&k2en=hg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'werkzeug_debugger_runserver',
    'django_extensions',
    'bootstrap3',
    'captcha',
    'PdfWeb',
    'PdfWeb.templatetags.tagfilter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '%s.urls' % PROJECT_NAME

WSGI_APPLICATION = 'PdfWeb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alvin',
        'USER': 'root',
        'PASSWORD':'xc19901109',
        'HOST':'192.168.31.103',
        'PORT':'3306',
    }
}
#root,xc900923

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

EMAIL_USE_SSL = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '1244785530@qq.com'
EMAIL_HOST_PASSWORD = 'huadrdgbevcyijeh'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONFIRM_DAYS = 7


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = ( 
    os.path.join(PARENT_DIR,'static'),
)
# 鍥剧墖鍌ㄥ瓨鏍硅矾寰�
MEDIA_ROOT = os.path.join(PARENT_DIR,'media')
# 鍥剧墖璁块棶url
MEDIA_URL = '/media/'

MDEDITOR_CONFIGS = {
'default':{
    'width': '90%',  # 鑷畾涔夌紪杈戞瀹藉害
    'heigth': 500,   # 鑷畾涔夌紪杈戞楂樺害
    'toolbar': ["undo", "redo", "|",
                "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
                "h1", "h2", "h3", "h5", "h6", "|",
                "list-ul", "list-ol", "hr", "|",
                "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
                "emoji", "html-entities", "paalvinentities", "|", "goto-line",
                "help", "info",
                "||", "preview", "watch", "fullscreen"],  # 鑷畾涔夌紪杈戞宸ュ叿鏍�
    'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],  # 鍥剧墖涓婁紶鏍煎紡绫诲瀷
    'image_folder': 'article',  # 鍥剧墖淇濆瓨鏂囦欢澶瑰悕绉�
    'theme': 'default',  # 缂栬緫妗嗕富棰� 锛宒ark / default
    'preview_theme': 'default',  # 棰勮鍖哄煙涓婚锛� dark / default
    'editor_theme': 'default',  # edit鍖哄煙涓婚锛宲astel-on-dark / default
    'toolbar_autofixed': True,  # 宸ュ叿鏍忔槸鍚﹀惛椤�
    'search_replace': True,  # 鏄惁寮�鍚煡鎵炬浛鎹�
    'emoji': True,  # 鏄惁寮�鍚〃鎯呭姛鑳�
    'tex': True,  # 鏄惁寮�鍚� tex 鍥捐〃鍔熻兘
    'flow_chart': True,  # 鏄惁寮�鍚祦绋嬪浘鍔熻兘
    'sequence': True,  # 鏄惁寮�鍚簭鍒楀浘鍔熻兘
    'watch': True,  # 瀹炴椂棰勮
    'lineWrapping': False,  # 鑷姩鎹㈣
    'lineNumbers': True  # 琛屽彿
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PARENT_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'builtins':['django.templatetags.static']
        },
     
    },
]

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.load_template_source',
    'django.template.loaders.app_directories.load_template_source',
)